version: '3.8'
services:
  node_backend: 
    container_name: node_backend
    build: .
    ports:
      - '3030:3030'
      - '8080:8080'
    environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=securepassword
    - DBNAME=forex_db
    - DB_HOST=db
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    depends_on: 
      - db
      - redis
  db:
    image: postgres:12.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=forex_db
    ports:
      - '5430:5430'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6378:6378'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  db:
    driver: local
  node_backend:
  redis:
    driver: local