version: '3.8'
services:
  node_backend: 
    container_name: node_backend
    build: .
    ports:
      - '3030:3030'
      - '8080:8080'
    environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=securepassword
    - DBNAME=forex_db
    - DB_HOST=db
    depends_on: 
      - db
  db:
    image: postgres:12.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=forex_db
    ports:
      - '5431:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  node_backend: